

version: 2

sources:
  - name: raw_data
    database: SLEEKMART_OMS
    schema: L1_LANDING
    tables:
      - name: CUSTOMERS
      - name: ORDERS
      - name: ORDERITEMS
      - name: DATES
      - name: EMPLOYEES
      - name: PRODUCTS
      - name: STORES
      - name: SUPPLIERS